/**
 * Set Qlik Sense Server configuration
 */
var SENSE_CONF = {
    hostname: 'ukwin-aor-w10', // window.location.hostname, //Modify if SENSE runs on a different machine
    isSecure: true,
    prefix: '/ondemand/' //Virtual proxy
};


//-----------------------------------------------------------------

var SENSE_URL_RESOURCES = ((SENSE_CONF.isSecure)? "https://" : "http://") + SENSE_CONF.hostname + SENSE_CONF.prefix + "resources/";

function injectScript(src) {
     return new Promise((resolve, reject) => {
		const script = document.createElement('script');
		script.async = true;
		script.src = src;
		script.addEventListener('load', resolve);
		script.addEventListener('error', () => reject('Error loading script.'));
		script.addEventListener('abort', () => reject('Script loading aborted.'));
		document.head.appendChild(script);
     });
}


injectScript(SENSE_URL_RESOURCES + "assets/external/requirejs/require.js")
	.then(() => {

		//Configure requireJS base url to load Sense resources
		require.config({
			baseUrl: SENSE_URL_RESOURCES
		});

		injectScript("bower_components/angular-ui-router/release/angular-ui-router.min.js");
		injectScript("bower_components/angular-cookies/angular-cookies.min.js");
		injectScript("bower_components/angular-busy/dist/angular-busy.min.js");

		injectScript("app.js");
		injectScript("login/login.js");
		injectScript("dashboard/dashboard.js");
	}).catch(error => {
		console.log(error);
	});

//Load Qlik Sense styles
(function() {
     var head = document.getElementsByTagName('head')[0];
     var link = document.createElement('link');
     link.rel = 'stylesheet';
     link.type = 'text/css';
     link.href = SENSE_URL_RESOURCES + "autogenerated/qlik-styles.css";
     head.appendChild(link);
})();
